version: '3.8'

services:
  web:
    build: .
    ports:
      - "5123:5123"
    volumes:
      - .:/app
    environment:
      - OPENAI_API_KEY=your_openai_api_key_here
      - OPENAI_PROMPT=your_prompt_here
