version: '3.8'

services:
  web:
    build: .
    ports:
      - "5123:5123"
    volumes:
      - .:/app
    environment:
      - OPENAI_API_KEY=your_openai_api_key_here
      - OPENAI_PROMPT=Extract details: Date, Time, Ticket Number, Issuing Company, Truck Number (Australia), Waste Name, Gross Weight, Tare Weight, Net Weight in JSON format.

